jobs:
  - job: deploy_docs
    displayName: 'Deploy docs'
    steps:
      - template: ci/azure-install-rust.yml
      - template: ci/azure-install-node.yml
      - template: ci/azure-cache-rust-deps.yml
      - script: cargo install --git https://github.com/steveklabnik/wrangler --branch upload-static
        displayName: 'Install Wrangler'
      - script: npm install
        displayName: 'Install NPM dependencies'
      - script: bin/hugo
        displayName: 'Build Hugo site'
      - script: wrangler config $env:CF_EMAIL $env:CF_API_KEY
        displayName: 'Configure Wrangler'
        env:
          CF_EMAIL: $(CF_EMAIL)
          CF_API_KEY: $(CF_API_KEY)
      - script: cd worker && wrangler upload-static-files STATIC_CONTENT ../public/
        displayName: 'Publish website'
