name: Deploy staging site

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Navigate to repo
      run: cd $GITHUB_WORKSPACE
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install deps
      run: npm install
    - name: Install Hugo
      run: sudo snap install hugo
    - name: Copy config for hugo
      run: cp config-staging.toml config.toml
    - name: Build docs
      run: hugo
    - name: Publish
      uses: cloudflare/wrangler-action@1.1.0
      with:
        apiKey: ${{ secrets.CF_API_KEY }}
        email: ${{ secrets.CF_EMAIL }}
        wranglerVersion: '1.6.0'
        environment: "staging"
