name: Build site

on:
  pull_request:
    branches:
    - master
    - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Navigate to repo
      run: cd $GITHUB_WORKSPACE
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install deps
      run: npm install
    - name: Install Wrangler
      run: npm i @cloudflare/wrangler@1.5.0 -g
    - name: Install Workers script deps
      run: npm install
    - name: Build docs
      run: npm run build
    - name: Build Workers script
      run: wrangler build
